### ISSUE TITLE
Styling clock

### ISSUE THREAD

**Issue by jotafelix** [abdulkhaderp/react-digital-clock#1]
Hi, I'm trying to style the clock but I am not able to do it. I am using React and Gatsby and I set the Clock and included a class where I set the color.

I tried by using emotion plugin and setting the color inside the css class, none worked. Can you please let me know how can I style <Clock /> ?

Thank you!

**Comment by abdulkhaderp** [comment]
Hi @jotafelix ,

Please wrap the component in a div with a css class, then style using it. 
For example,  
HTML :  `<div class="digiClock"> <Clock /> </div>`
CSS    :  `.digiClock div { color : red !important; font-size :17 px; }` ( For color and text-align, use !important)

Hope it solve your problem !

**Comment by jotafelix** [comment]
it worked @abdulkhaderp , thank you for your help!
